package com.example.candyanimation.base

const val TAG_LOG = "LOG_TAG_CANDY"

const val HARDCODED_NOTIFICATIONS_COUNT = 3

const val CATEGORY_RV_CIRCLE_ICON_ROTATION_SPEED_RESTRAIN_VALUE = 2

const val PRODUCTS_RV_ITEM_IMAGE_CORNER_RADIUS = 25

